[package]
name = "advent-of-code-answers"
version = "0.1.0"
edition = "2021"


[dependencies]
itertools = "*"
pretty_assertions = "*"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
